
Create table users
(
uid integer,
email varchar(254) not null,--this is the max length of an email with domain
fName varchar(35),
lName varchar(35),
--uIC1:userID is the primary key - generated by app - no two will be the same
constraint uIC1 primary key(uid)
--uIC2:
);

Create table conversation
(
  cid integer not null,
  constraint cIC1 primary key(cid)
);

Create table message --this is a weak entity
(
  timeSent time not null, --part of key
  muid integer not null, --message user id - part of key
  mcid integer not null, --part of key - message conversation id
  txt text not null --contents of the message - contains text and cannot send a null message
  --create constraints - weak entity defined by timesent, user.uid, conversation.cid
  constraint messagePKey primary key (timeSent),
  constraint messageForeignKey1 foreign key(muid) references user(uid),
  constraint messageForeignKey2 foreign key(mcid) references conversation(mcid)
);

Create table media  --can only send one media per message
(
  timeSent time not null, --foreign key
  muid integer not null, --foreign key
  mcid integer not null, --foreign key
  fileType varchar(4),
  fileName varchar(260),

  --Constraints:
  constraint mediaFkey foreign key(muid, mcid, timeSent) references message(muid, mcid, timeSent)
);

Create table takesPartIn
(
  uid integer not null,
  cid integer not null,

--foreign keys from user and conversation
  constraint userForeignKey foreign key(uid) references users(uid),
  constraint convForeignKey foreign key(cid) references conversation(cid)
);

