DROP TABLE takesPartIn CASCADE CONSTRAINTS;
DROP TABLE media CASCADE CONSTRAINTS;
DROP TABLE message CASCADE CONSTRAINTS;
DROP TABLE conversation CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS; 
